x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.2-python3.10
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - PYTHONPATH=/opt/airflow
    - AIRFLOW_UID=0
  volumes:
    - ./dags:/opt/airflow/dags
    - data:/opt/airflow/data
    - logs:/opt/airflow/logs
    - /var/run/docker.sock:/var/run/docker.sock
  user: "0:0"
  restart: always
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - etl_net

  etl-postgres:
    image: postgres:15
    container_name: etl-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - etl-db:/var/lib/postgresql/data
    networks:
      - etl_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - etl_net

  init-db:
    image: postgres:15
    depends_on:
      - etl-postgres
    volumes:
      - ./sql:/sql
      - ./bin/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    entrypoint: [ "bash", "/docker-entrypoint-initdb.d/init_db.sh" ]
    networks:
      - etl_net

  init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.org"
    networks:
      - etl_net
  

  scheduler:
    <<: *airflow-common
    command: scheduler
    networks:
      - etl_net

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - etl_net

volumes:
  postgres-db:
  etl-db:
  pgadmin-data:
  logs:
  data:

networks:
  etl_net:
    name: etl_net